### ISSUE TITLE
Option to report coverage back via GH api?

### ISSUE THREAD

**Issue by GitMensch** [danielealbano/lcov-action#6]
When running this action on PR it _seems_ the code coverage will be only be shown in the action console output.
Can you report it back to the UI (so something like "code coverage is XXX")? Maybe optionally run `genhtml` to produce the output as HTML, adding it as artifact and providing the link back to the UI?

**Comment by GitMensch** [comment]
Thank you for the prompt answer - maybe you can add a bit of that to the action description?

> GitHub doesn't provide a functionality to do that but I use it in combination with codecov and I get comments dropped in the PRs with the code coverage.

Can an action "comment", too - or is it only the external service that uses the GH API to do so?
If this could be an optional step "report to PRs" this would be nice, but codecov looks quite nice, too (I guess it would really be useful to hint at the combination in the README).

For the optional generation of genhtml and providing as artifact - as noted this would be only an optional thing, which gitlab users may not use. Until then the workaround is add two steps, one that manually invokes `LANG=C genhtml  --prefix . --output-directory "ci-coverage" --title CI "Code Coverage" --legend --show-details "coverage.info" --rc genhtml_branch_coverage=1` and another that `uses: actions/upload-artifact@v3` to upload the complete resulting folder.
As this action has the path and names setup I think that would be a useful addition.

Question: The codecov@v3 action https://github.com/codecov/codecov-action#usage has a `gcov` option - would this mean that using v3 with that option makes this action only necessary for the additional tweaking options?

**Comment by danielealbano** [comment]
As far I am aware you need to use APIs to drop / update comments in PRs, the action can simply issue a request if it wants to, in general an action it's just some code running in a pipeline, nothing more.

The suggestion about adding codecov to the documentation is great, will update the readme, thanks!

> For the optional generation of genhtml and providing as artifact - as noted this would be only an optional thing, which gitlab users may not use. Until then the workaround is add two steps, one that manually invokes LANG=C genhtml --prefix . --output-directory "ci-coverage" --title CI "Code Coverage" --legend --show-details "coverage.info" --rc genhtml_branch_coverage=1 and another that uses: actions/upload-artifact@v3 to upload the complete resulting folder.
> As this action has the path and names setup I think that would be a useful addition.

The suggestion is great, do you want to make a PR for it?

> Question: The codecov@v3 action https://github.com/codecov/codecov-action#usage has a gcov option - would this mean that using v3 with that option makes this action only necessary for the additional tweaking options?

At the time I got some issues with gcov so I decided to use lcov and create this action

**Comment by GitMensch** [comment]
> The suggestion is great, do you want to make a PR for it?

"monkey see, monkey do" - I should be able to add the optional configuration coverage-html, if set to "true", then coverage is done, with optional configurations for output directory and title (all others).

One new optional configuration would enable branch-coverage (in both outputs), and the final "cp" would be replaced by a "mv".

Should I try to add the upload, too - or do we leave that to the upload-artifact action which may be used later I only could have a look into its source and possibly copy parts of it here)?

What do you think?
Note: I'd do the changes and a PR but would not do any in-depth tests.

**Comment by GitMensch** [comment]
All questions answered, follow-up issues with actual TODOs created -> closed.
